#if defined _main_included
	#endinput
#endif
#define _main_included

//MAIN: contains default logic and constants
#include "main/color.inc"
#include "main/math.inc"
#include "main/string.inc"
#include "main/calendar.inc"
#include "main/invalid.inc"
#include "main/virtualworld.inc"
#include "main/interior.inc"
#include "main/weather.inc"
#include "main/time.inc"
#include "main/class.inc"
#include "main/vehicle.inc"
#include "main/weapon.inc"
#include "main/player.inc"
#include "main/audiostream.inc"
#include "main/zone.inc"

//CUSTOM: contains custom logic and constants
#include "main/custom/interior.inc"
#include "main/custom/vehicle.inc"