#if defined _util_included
	#endinput
#endif
#define _util_included

#include <a_samp>

// MAIN: Contains default logic and constants
#include "util/color.inc"
#include "util/math.inc"
#include "util/string.inc"
#include "util/calendar.inc"
#include "util/invalid.inc"
#include "util/limit.inc"
#include "util/textdraw.inc"
#include "util/dialog.inc"
#include "util/virtualworld.inc"
#include "util/interior.inc"
#include "util/weather.inc"
#include "util/time.inc"
#include "util/class.inc"
#include "util/vehicle.inc"
#include "util/weapon.inc"
#include "util/player.inc"
#include "util/audiostream.inc"
#include "util/zone.inc"

// CUSTOM: Contains custom logic and constants
#include "util/custom/interior.inc"
#include "util/custom/vehicle.inc"