#if defined _maincolor_included
	#endinput
#endif
#define _maincolor_included

// COLORS FROM SINGLE PLAYER
/**
 * -DESCRIPTION:
 * 		-Defines some colors from single player.
 */
#define COLOR_SP_MAPICON_ENEMY				0xb31a1eff // Red from mapicon enemy
#define COLOR_SP_MAPICON_ALLY				0x343d7eff // Blue from mapicon ally
#define COLOR_SP_MAPICON_OBJECTIVE			0xe2c063ff // Yellow from mapicon objective
#define COLOR_SP_GAMETEXT_RED				0x9c1634ff // Red from gametext ~r~
#define COLOR_SP_GAMETEXT_BLUE				0x2b346eff // Blue from gametext ~b~
#define COLOR_SP_GAMETEXT_YELLOW			0xc4a656ff // Yellow from gametext ~y~
#define COLOR_SP_HEALTH_FG					0xb4191dff // Red from healthbar foreground
#define COLOR_SP_HEALTH_BG					0x5a0c0eff // Red from healthbar background
#define COLOR_SP_ARMOUR_FG					0xe1e1e1ff // Grey from armourbar foreground
#define COLOR_SP_ARMOUR_BG					0x707070ff // Grey from armourbar background
#define COLOR_SP_BREATH_FG					0xaccbf1ff // Blue from breathbar foreground
#define COLOR_SP_BREATH_BG					0x566578ff // Blue from breathbar background
#define COLOR_SP_MONEY						0x2f5a26ff // Green from money
#define COLOR_SP_CLOCK						0xc3c3c3ff // Grey from clock

// DEFAULT DIALOG INFO TEXT COLOR
/**
 * -DESCRIPTION:
 * 		-Defines the default dialog info text color used by SA-MP.
 * -NOTES:
 * 		-Uses the '_NORMAL' naming scheme instead of the '_DEFAULT' naming scheme, to be in line with the naming scheme used by SA-MP for e.g. fighting styles.
 */
#define COLOR_DIALOG_INFO_NORMAL			0xa9c4e4ff // Light Blue

// LOG TEXT COLOR
/**
 * -DESCRIPTION:
 * 		-Defines the log text color used by SA-MP.
 */
#define COLOR_LOG							0xa9c4e4ff // Light Blue