#if defined _maindialog_included
	#endinput
#endif
#define _maindialog_included

// DIALOG AMOUNT LIMIT
/**
 * -DESCRIPTION:
 * 		-Defines the dialog amount limit.
 */
#define MAX_DIALOGS							32768

// TEXT DRAW CAPTION LIMIT
/**
 * -DESCRIPTION:
 * 		-Defines the text draw caption limit.
 */
#define MAX_DIALOG_CAPTION					64

// TEXT DRAW INFO LIMIT
/**
 * -DESCRIPTION:
 * 		-Defines the text draw info limit.
 */
#define MAX_DIALOG_INFO						4096

// TEXT DRAW BUTTON TEXT LIMIT
/**
 * -DESCRIPTION:
 * 		-Defines the text draw button text limit.
 * -NOTES:
 * 		-This is not the actual limit, but the button is only 10 characters wide.
 */
#define MAX_DIALOG_BUTTON_TEXT				10

// TEXT DRAW INPUT LIMIT
/**
 * -DESCRIPTION:
 * 		-Defines the text draw input limit.
 */
#define MAX_DIALOG_INPUT					128

// TEXT DRAW COLUMN LIMIT
/**
 * -DESCRIPTION:
 * 		-Defines the text draw column limit.
 */
#define MAX_DIALOG_COLUMNS					4

// TEXT DRAW COLUMN NAME LIMIT
/**
 * -DESCRIPTION:
 * 		-Defines the text draw column name limit.
 */
#define MAX_DIALOG_COLUMN_NAME				128

// TEXT DRAW ROW TEXT LIMIT
/**
 * -DESCRIPTION:
 * 		-Defines the text draw row text limit.
 */
#define MAX_DIALOG_ROW_TEXT					256