#if defined _maininvalid_included
	#endinput
#endif
#define _maininvalid_included

// UNRELATED INVALID IDs
/**
 * -DESCRIPTION:
 * 		-Defines some unrelated invalid IDs.
 * -NOTES:
 * 		-Other invalid IDs are defined in the file of the entity to which they belong.
 */
#define INVALID_SKIN_ID						-1
#define INVALID_MODEL_ID					-1
#define INVALID_CHECKPOINT_ID				-1
#define INVALID_MAPICON_ID					-1
#define INVALID_PICKUP_ID					-1
#define INVALID_AREA_ID						-1
#define INVALID_TIMER_ID					-1