#if defined _mainlimit_included
	#endinput
#endif
#define _mainlimit_included

// UNRELATED LIMITS
/**
 * -DESCRIPTION:
 * 		-Defines some unrelated limits.
 * -NOTES:
 * 		-Other limits are defined in the file of the entity to which they belong.
 */
#define MAX_CHECKPOINTS						1
#define MAX_RACE_CHECKPOINTS				1
#define MAX_MAPICONS						100
#define MAX_OBJECT_MATERIAL_TEXT			2048
#define MAX_PLAYER_VARIABLES				800
#define MAX_GAMEMODES						16
#define MAX_FILTERSCRIPTS					16