#if defined _maintextdraw_included
	#endinput
#endif
#define _maintextdraw_included

//TEXT DRAW TEXT LIMIT
/**
 * -DESCRIPTION:
 * 		-Defines the text draw text limit.
 */
#define MAX_TEXT_DRAW_TEXT					1024

//TEXT DRAWS SHOWN LIMIT
/**
 * -DESCRIPTION:
 * 		-Defines the text draws shown limit.
 */
#define MAX_TEXT_DRAWS_SHOWN				MAX_TEXT_DRAWS+MAX_PLAYER_TEXT_DRAWS

//TEXT DRAW SPRITES SHOWN LIMIT
/**
 * -DESCRIPTION:
 * 		-Defines the text draw sprites shown limit.
 */
#define MAX_TEXT_DRAW_SPRITES_SHOWN			100